name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "news"
database_name = "newsnow-db"
database_id = "3a391115-2d59-4571-86e0-1866b2eb8d98"
